Repository Soujanya2004/wanderlust-2024, pull requests merged in 2024-10, with the labels that each got.

#44 Update README.md
  README.md
Labels: gssoc-ext, level1

#48 Added the Confirm Password issue #39
  views/signup.ejs
Labels: gssoc-ext, level2

#50 Fixed : Missing Contributing.md
  Contributing.md
Labels: gssoc-ext, level2

#49 Implement CORS for Cross-Origin Resource Sharing in the Backend
  app.js
  package-lock.json
  package.json
Labels: gssoc-ext, level2

#63 [FIX] #43
  views/show.ejs
Labels: gssoc-ext, level1

#67 Added PR/ISSUE- TEMPLATE
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/Pull_Request_Template.md
  .github/workflows/autocomment-iss-close.yml
  .github/workflows/autocomment-pr-merge.yml
  .github/workflows/autocomment-pr-raise.yml
  .github/workflows/close-old-issue.yml
  .github/workflows/close-old-pr.yml
  .github/workflows/greetings.yaml
Labels: gssoc-ext, level3

#54 Fix/updated documentation
  .gitignore
  README.md
  app.js
Labels: gssoc-ext, level3

#68 Hosted the Website on Render
  README.md
Labels: gssoc-ext, level3

#73 feat:Central messages
  constants.js
  controllers/listing.js
  controllers/reviews.js
  middlewares/middleware.js
Labels: gssoc-ext, level2

#69 About page added
  app.js
  package-lock.json
  package.json
  views/about.ejs
  views/includes/navbar.ejs
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, level2

#65 Create auto-comment-issue.yml
  .github/workflow/auto-comment-issue.yml
Labels: gssoc-ext, level2

#72 enhance the search box #33
  app.js
  controllers/listing.js
  views/includes/navbar.ejs
  views/search.ejs
Labels: gssoc-ext, level1

#79 Update README.md
  README.md
Labels: gssoc-ext, level1

#77 Add: "auto-label" GitHub Workflow for Automated Labeling
  .github/workflows/auto-label.yml
Labels: gssoc-ext, level2

#84 Update README.md and Contributor section #82
  README.md
Labels: gssoc-ext, level1

#89 Improve Nav UI|Rresponsiveness
  public/css/styles.css
  views/includes/navbar.ejs
Labels: gssoc-ext, level2

#90 Fix the ISSUE of #58 . Improvement of review section from scratch.
  public/css/review.css
  public/user (1).png
  views/show.ejs
Labels: gssoc-ext, level2

#94 Add Customized Footer for Improved User Experience
  public/css/styles.css
  views/about.ejs
  views/includes/footer.ejs
Labels: gssoc-ext, level1

#99 Add listing Bug Fix
  app.js
  controllers/listing.js
  package-lock.json
  views/new.ejs
Labels: gssoc-ext, level3

#100 Fix the Review Submission Error
  app.js
  controllers/reviews.js
  views/show.ejs
Labels: gssoc-ext, level3

#107 Add Custom 404 Page Not Found
  app.js
  public/404.png.png
  views/not_found.ejs
Labels: gssoc-ext, level1

#108 imrprove show listing UI with responsiveness
  views/show.ejs
Labels: gssoc-ext, level2

#110 Add Responsiveness to Whole Website (#103)
  views/index.ejs
Labels: gssoc-ext, level3

#111 fixing the "Delete Button" in the review section
  views/show.ejs
Labels: gssoc-ext, level2

#115 Enhancing the responsive design for the slide bar
  public/css/styles.css
  views/index.ejs
Labels: gssoc-ext, level2

#116 Dynamic copyright
  views/includes/footer.ejs
Labels: level2

#109 Improve UI for Review showing section with responsiveness (#16)
  public/css/styles.css
  views/show.ejs
Labels: gssoc-ext, level2

#129 preventing listing owners from reviewing their own listing (#118)
  views/show.ejs
Labels: gssoc-ext, level2

#130 added a new page to display all contributors
  contributor/contributor.css
  contributor/contributor.html
  contributor/contributor.js
  views/includes/navbar.ejs
Labels: gssoc-ext, level3

#133 Dark Mode Implementation for /listing route mainly (#14)
  public/css/dark_mode.css
  public/css/light_mode.css
  public/css/styles.css
  public/js/toggler.js
  views/includes/navbar.ejs
  views/index.ejs
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, level2

#151 dark mode implementation on the /privacy page (#135)
  views/privacy.ejs
Labels: gssoc-ext, level2

#150 About page
  views/about.ejs
Labels: gssoc-ext, level2

#152 adding dark mode on the /terms page (#136)
  views/terms.ejs
Labels: gssoc-ext, level2

#159 dark mode on the Edit Listing page (#156)
  views/edit.ejs
Labels: gssoc-ext, level1, level2

#154 implementing dark mode on the sign-up page ((#139)
  views/login.ejs
  views/signup.ejs
Labels: gssoc-ext, level1, level2

#155 Adding Dark Mode for New Listing Page (#140)
  views/new.ejs
Labels: gssoc-ext, level2

#157 Changes for updating map pointer in edit route ISSUE #81
  controllers/listing.js
Labels: gssoc-ext, level2

#158 Adding dark mode on the Show Listing page
  views/show.ejs
Labels: gssoc-ext, level2

#162 Added dark mode on the /contributors page (#137)
  views/contributors.ejs
Labels: gssoc-ext, level2

#164 Add logic from review spamming ISSUE #78
  controllers/listing.js
  controllers/reviews.js
  views/show.ejs
Labels: gssoc-ext, level2, level3

#165 Toggle bug
  public/js/toggler.js
Labels: gssoc-ext, level3

#167 Add My Profile Page (#114)
  app.js
  public/profile.png
  views/includes/navbar.ejs
  views/profile.ejs
Labels: gssoc-ext, level2, level3

#185 Create LICENSE
  LICENSE
Labels: gssoc-ext, level2

#186 Added dark mode for the "Page Not Found" page (#181)
  views/not_found.ejs
Labels: gssoc-ext, level2

#187 Delete duplicate edit option (#179)
  views/profile.ejs
Labels: gssoc-ext, level1

#189 Add success & failure form validation message
  views/new.ejs
Labels: gssoc-ext, level2

#203 change the button color
  views/includes/navbar.ejs
Labels: gssoc-ext, level1

#188 Adjusting the listing card alignment, ( #178)
  public/css/styles.css
  views/index.ejs
Labels: gssoc-ext, level2

#190 Fix & redesign the new property add form.
  views/new.ejs
Labels: gssoc-ext, level1, level2

#198 Design signin signup
  controllers/listing.js
  public/css/styles.css
  public/noprofilenav.png
  public/profilenav.png
  views/includes/navbar.ejs
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, level1, level2

#207 Add animation on accordion in index page ISSUE #146
  public/css/styles.css
  views/index.ejs
Labels: gssoc-ext, level2

#211 Redesign Navbar (#131)
  public/css/styles.css
  views/includes/navbar.ejs
Labels: gssoc-ext, level2

#208 Feature enhancement for No review ISSUE #127
  public/css/dark_mode.css
  views/includes/navbar.ejs
  views/show.ejs
Labels: gssoc-ext, level2

#210 Added Table to Display Repository Statistics in README.md
  README.md
Labels: gssoc-ext, level2

#213 completed
  README.md
Labels: gssoc-ext, level1, level2, level3

#218 Feature/password toggle
  .env
  .gitignore
  public/css/light_mode.css
  public/js/script.js
  views/layouts/boilerplate.ejs
  views/login.ejs
  views/signup.ejs
Labels: gssoc-ext, level1

#216 Redesign edit form
  views/edit.ejs
Labels: gssoc-ext, level2

#223 Change darkmode toggle icon. Also replace the icon from fontawesome to boxiicon
  public/css/styles.css
  public/js/toggler.js
  views/includes/navbar.ejs
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, level1

#224 Feature implemented Go to top button. ISSUE #160
  public/css/styles.css
  public/js/script.js
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, level2

#227 Fix the text visibility and card background color in darkmode. ISSUE #147
  views/contributors.ejs
  views/show.ejs
Labels: gssoc-ext, level2

#228 Change the position of the dark mode toggle button and also redesign it from scratch. ISSUE #172
  public/css/styles.css
  public/js/toggler.js
  views/includes/navbar.ejs
Labels: gssoc-ext, level2

#229 Update the Page not found page and make it available for all situation
  public/400.png
  views/not_found.ejs
Labels: gssoc-ext, level2

#230 adding profile pic upload functionality (#169)
  app.js
  models/user.js
  package-lock.json
  package.json
  uploads/1729917570542-download (5).jpeg
  uploads/1729917909217-gettyimages-1540766473-612x612 (1).jpg
  uploads/1729918110084-download (5).jpeg
  uploads/1729918126379-gettyimages-1540766473-612x612 (1).jpg
  uploads/1729918239312-gettyimages-1540766473-612x612 (1).jpg
  uploads/1729918242184-download (5).jpeg
  views/profile.ejs
Labels: gssoc-ext, level3

#226 All buttons looks good ISSUE #128
  views/login.ejs
  views/show.ejs
  views/signup.ejs
Labels: gssoc-ext, level1

#231 Fix Profile Editing Functionality (#171) and (#170)
  app.js
  views/editprofile.ejs
Labels: gssoc-ext, level3

#235 Added GitHub Workflow for Auto-Closing Similar Issue Requests
  .github/workflows/detect-duplicate-issues.yml
Labels: gssoc-ext, level2

#233 UI and Dark Mode Fixes (#221 & #222)
  views/login.ejs
  views/signup.ejs
Labels: gssoc-ext, level1

#242 Dark Mode Functionality for Edit Profile Form (#232)
  .env
  uploads/1729917570542-download (5).jpeg
  uploads/1729917909217-gettyimages-1540766473-612x612 (1).jpg
  uploads/1729918110084-download (5).jpeg
  uploads/1729918126379-gettyimages-1540766473-612x612 (1).jpg
  uploads/1729918239312-gettyimages-1540766473-612x612 (1).jpg
  uploads/1729918242184-download (5).jpeg
  views/editprofile.ejs
Labels: gssoc-ext, level1

#247 Change the all font
  public/css/styles.css
Labels: gssoc-ext, level1

#249 Responsive of show page in small screen
  public/css/styles.css
  views/show.ejs
Labels: gssoc-ext, level2

#250 Change in price field. Make it type number only
  views/new.ejs
Labels: gssoc-ext, level1

#251 Fixed Duplicate description field
  views/new.ejs
Labels: gssoc-ext, level1

#256 Add Toggle Button for Total Price Including GST on Listings Page (Fixes #241)
  views/index.ejs
Labels: gssoc-ext, level3

#258 Redesign whole index page
  public/css/dark_mode.css
  public/css/light_mode.css
  public/css/styles.css
  views/includes/footer.ejs
  views/index.ejs
  views/layouts/boilerplate.ejs
  views/show.ejs
Labels: gssoc-ext, level3

#259 Fixed Password toggle and improve the UI of sign up page.
  public/css/dark_mode.css
  public/js/script.js
  views/signup.ejs
Labels: gssoc-ext, level2

#260 Fix the Search result UI along with responsiveness.
  views/index.ejs
  views/search.ejs
Labels: gssoc-ext, level2

#265 Change position of the flash msg
  views/includes/flash.ejs
Labels: gssoc-ext, level1

#271 Change profile picture
  public/profile.png
Labels: gssoc-ext, level1

#274 Fix login form
  app.js
  utils/error.js
  views/login.ejs
Labels: gssoc-ext, level2

#282 Profile pic upload functionality
  app.js
  models/user.js
  views/editprofile.ejs
  views/profile.ejs
Labels: gssoc-ext, level3

#289 Add responsiveness in profile page
  views/profile.ejs
Labels: gssoc-ext, level2

#290 Passwords synchronization in sign up page
  app.js
  public/js/script.js
  views/signup.ejs
Labels: gssoc-ext, level2

#291 Make this profile edit form responsive along with UI enhancement
  views/editprofile.ejs
Labels: gssoc-ext, level1

#292 New List create and Edit list, both form responsive and enhancing UI
  public/css/styles.css
  views/edit.ejs
  views/includes/footer.ejs
  views/new.ejs
Labels: gssoc-ext, level2

#293 Feat: Adding ContactUs Backend functionality using Nodemailer
  .env.example
  app.js
  controllers/contactUs.js
  mail/template/contactFormRes.js
  package.json
  views/contact.ejs
Labels: gssoc-ext, level3

#299 Make Login signup form responsive
  views/login.ejs
  views/signup.ejs
Labels: gssoc-ext, level2

#276 updating CSS for GST toggle button (#257)
  views/index.ejs
Labels: gssoc-ext, level1

#300 Fix the error in profile edit route
  app.js
  views/editprofile.ejs
Labels: gssoc-ext, level3

#303 Customize profile picture URL to reduce loading time.
  app.js
  models/user.js
  views/includes/navbar.ejs
  views/profile.ejs
Labels: gssoc-ext, level2

#308 Dark Mode for Manage Listings Page (#277)
  package-lock.json
  views/adminDashboard.ejs
Labels: gssoc-ext, level1

#309 Dark Mode for Manage Users Page (#278)
  views/manageUser.ejs
Labels: gssoc-ext, level1

#310 Added scroll up btn
  README.md
Labels: gssoc-ext, level1

#312 table of contents fix
  README.md
Labels: gssoc-ext, level1
