Repository Soujanya2004/wanderlust-2024, pull requests merged in 2024-11, with the labels that each got.

#314 Profile Picture availability in navbar
  app.js
  public/css/styles.css
  views/includes/navbar.ejs
Labels: gssoc-ext, level2

#315 Profile picture available on Show page owner
  views/show.ejs
Labels: gssoc-ext, level2

#316 Profile pic availability for all Reviewer
  public/reviewer.png
  views/show.ejs
Labels: gssoc-ext, level2

#325 ✅ [Feature Request]: Add stargazers timeline
  contributor/contributor.html
  public/assets/wanderlust.mp4
  public/css/contributor.css
Labels: gssoc-ext, level2

#324 Add some screenshots
  README.md
Labels: gssoc-ext, level1

#326 Multiple Image Upload Implementation (#313)
  cloudConfig.js
  controllers/listing.js
  models/listing.js
  package-lock.json
  views/index.ejs
  views/new.ejs
Labels: gssoc-ext, level3

#330 ✅ Contributor.js file done
  contributor/contributor.html
  contributor/contributor.js
  public/css/contributor.css
Labels: gssoc-ext, level2

#331 Delete profile picture functionality
  app.js
  views/editprofile.ejs
Labels: gssoc-ext, level2

#332 Restructure the contact us form
  views/contact.ejs
Labels: gssoc-ext, level2

#339 Add "View Detailed Profile" Option from Manage Listings (#279)
  app.js
  views/adminDashboard.ejs
  views/manageUser.ejs
  views/view_manage_listing.ejs
Labels: gssoc-ext, level2

#344 Add "View Reviews" Option on Individual Listings with Backend Support (#280)
  app.js
  views/adminDashboard.ejs
  views/view_reviews.ejs
Labels: gssoc-ext, level3

#348 Backend for delete profile picture.
  app.js
  views/includes/navbar.ejs
Labels: gssoc-ext, level2

#349 Secure Admin Setup to Prevent Unauthorized Access (#346)
  admin.js
Labels: gssoc-ext, level3

#351 Add Feedback form
  public/css/styles.css
  public/js/script.js
  views/includes/footer.ejs
Labels: gssoc-ext, level3

#340 Fixed navbar to add HOME tag
  public/css/styles.css
  views/includes/navbar.ejs
Labels: gssoc-ext, level2

#357 Added Icons
  public/css/styles.css
  views/includes/navbar.ejs
Labels: gssoc-ext, level1

#359 PRELOADER..
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, level1

#362 Fix UI Misalignment in Manage Listings from Admin Dashboard
  views/adminDashboard.ejs
Labels: gssoc-ext, level2

#364 Stay logged in after change the profile details
  app.js
Labels: gssoc-ext, level3

#363 Fix the Navbar UI with Responsiveness (#361)
  views/includes/navbar.ejs
Labels: gssoc-ext, level1

#366 Review deletion error & website crash problem solved
  controllers/reviews.js
  middlewares/middleware.js
  views/show.ejs
Labels: gssoc-ext, level2

#367 Implement Dark Mode for "View Listing" Page in Admin Dashboard (#341)
  views/view_manage_listing.ejs
Labels: gssoc-ext, level1

#368 Dark Mode Implementation for Individual Listing's Review Page in Admin Dashboard (#345)
  views/view_reviews.ejs
Labels: gssoc-ext, level1

#371 Create Deployment link
  Deployment link
Labels: gssoc-ext, level3

#374 Dark mode implementation of edit listing form rendered from admin dashboard
  app.js
  views/edit_list_admin.ejs
Labels: gssoc-ext, level1

#381 Update Currency Symbol from Dollar to Rupee in View Listings and Reviews (#375)
  views/view_manage_listing.ejs
  views/view_reviews.ejs
Labels: gssoc-ext, level1

#382 Remove Edit Button for Managing User Profiles (#376)
  views/manageUser.ejs
Labels: gssoc-ext, level1

#384 Refactor Admin Dashboard to Include a Navbar Template on Each Page (#380)
  views/adminDashboard.ejs
  views/edit_list_admin.ejs
  views/includes/admin_navbar.ejs
  views/manageUser.ejs
  views/view_manage_listing.ejs
  views/view_reviews.ejs
Labels: gssoc-ext, level2

#386 Profile image fixed with hover effect.
  views/show.ejs
Labels: gssoc-ext, level2

#390 Add functionality of list image deletion in Edit
  controllers/listing.js
  views/edit.ejs
Labels: gssoc-ext, level2

#393 Add Listing Owner Name to Listing Page with Backend Integration for Individual Listings (#377)
  app.js
  views/adminDashboard.ejs
Labels: gssoc-ext, level2

#397 Add Preloader
  public/css/preloader.css
  public/js/script.js
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, level3

#398 Fix the owner profile pic section in show page
  views/show.ejs
Labels: gssoc-ext, level1

#402 Add model for large review content in show.ejs page.
  views/show.ejs
Labels: gssoc-ext, level3

#394 Visibility Issue for "Welcome To The Admin's Dashboard" Text on Hover in Dark Mode (#378)
  views/adminDashboard.ejs
Labels: gssoc-ext, level1

#406 Landing Page Design
  views/index.ejs
Labels: gssoc-ext, level3

#407 back to prev
  controllers/contactUs.js
  controllers/listing.js
  controllers/reviews.js
  public/js/contributor.js
  public/js/map.js
  public/js/script.js
  public/js/toggler.js
  views/about.ejs
  views/contact.ejs
  views/contributors.ejs
  views/privacy.ejs
  views/signup.ejs
  views/terms.ejs
  views/view_manage_listing.ejs
  views/view_reviews.ejs
Labels: gssoc-ext, level2

#409 Added proper Admin Dashboard Boilerplate to use across all pages (#379)
  views/adminDashboard.ejs
  views/edit_list_admin.ejs
  views/layouts/admin_boilerplate.ejs
  views/manageUser.ejs
  views/view_manage_listing.ejs
  views/view_reviews.ejs
Labels: gssoc-ext, level2

#414 Adjusted Visibility for "Welcome To The Admin's Dashboard" Text on Hover in Dark Mode (#395)
  views/adminDashboard.ejs
  views/includes/admin_navbar.ejs
Labels: gssoc-ext, level1

#413 Fix the error for loading
  app.js
  controllers/contactUs.js
  controllers/listing.js
  public/js/contributor.js
  public/js/map.js
  public/js/script.js
  public/js/toggler.js
  views/about.ejs
  views/contact.ejs
  views/contributors.ejs
  views/privacy.ejs
  views/signup.ejs
  views/terms.ejs
Labels: gssoc-ext, level3

#418 MODIFYING DEPLOYMENT LINK
  Deployment link
  controllers/listing.js
Labels: gssoc-ext, level3

#422 Chat bot Added
  README.md
  public/css/styles.css
  views/layouts/boilerplate.ejs
Labels: enhancement, gssoc-ext, level3

#424 Add clodinary destroyer to delete image in cloud space
  controllers/listing.js
Labels: gssoc-ext, level3

#416 Landing page routing update
  app.js
  views/index.ejs
  views/listing.ejs
Labels: gssoc-ext, level2

#428 Correct Navbar Misalignment on Small Screens (#396)
  views/includes/admin_navbar.ejs
Labels: gssoc-ext, level1

#430 Cloud destroyer for profile picture
  app.js
  views/editprofile.ejs
Labels: gssoc-ext, level2

#431 Add dark mode style for large review model
  public/css/styles.css
  views/show.ejs
Labels: gssoc-ext, level1

#429 Add Translator
  public/css/translator.css
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, level3

#432 Add Backend Functionality for Filter Icons Using Tags (#400)
  controllers/listing.js
  models/listing.js
  views/index.ejs
  views/new.ejs
Labels: gssoc-ext, level3

#435 FORGOT PASSWORD FEATURE..
  app.js
  mail/template/forgotpassword.js
  models/user.js
  views/forgot-password.ejs
  views/login.ejs
  views/resetPassword.ejs
Labels: gssoc-ext, level3

#450 Add Tag Editing Options to Update Listing with Backend Support (#433)
  app.js
  views/edit_list_admin.ejs
Labels: gssoc-ext, level2

#451 Display All Listings with Flash Message When No Results Found for Selected Filter (#439)
  controllers/listing.js
Labels: gssoc-ext, level1

#452 MADE CARD CLICKABLE
  views/index.ejs
Labels: gssoc-ext, level1

#453 Display Listing Tags in Admin Dashboard for Better Tag Management (#441)
  views/adminDashboard.ejs
Labels: gssoc-ext, level1

#459 Feedback backend
  .gitignore
  app.js
  controllers/feedback.js
  models/feedback.js
  public/js/script.js
  views/includes/footer.ejs
Labels: gssoc-ext, level3

#482 Re-structure the main server. Separate different route in different controllers
  app.js
  controllers/admin.js
  controllers/others.js
  controllers/profile.js
  controllers/user.js
Labels: gssoc-ext, level2

#484 ABOUT US PAGE
  views/about.ejs
Labels: gssoc-ext, level3

#485 Loader darkmode added
  .gitignore
  public/css/dark_mode.css
  public/css/light_mode.css
Labels: gssoc-ext, level1

#488 Addded forgot Password
  app.js
  package-lock.json
  package.json
Labels: gssoc-ext, level2

#501 ABOUT PAGE IN NAVBAR
  public/css/styles.css
  views/includes/navbar.ejs
Labels: gssoc-ext, level1

#504 Duplicate route removed.
  app.js
  controllers/listing.js
Labels: gssoc-ext, level1

#506 Set the lower resolution reviewer profile picture
  views/show.ejs
Labels: gssoc-ext, level1

#503 Enhance User Security by Adding Password Strength Validation to Registration Form (#471)
  views/signup.ejs
Labels: gssoc-ext, level3

#508 Fix the color
  views/index.ejs
Labels: gssoc-ext, level1

#509 Update Listing Section
  .gitignore
  app.js
  views/index.ejs
  views/listing.ejs
Labels: gssoc-ext, level2

#510 Fix Contributor Page to Display Total Contributors Correctly (#457)
  public/js/contributor.js
Labels: gssoc-ext, level1

#513 Feedback delete feature added for admin backend
  app.js
  controllers/admin.js
  views/includes/admin_navbar.ejs
  views/manageFeedback.ejs
Labels: gssoc-ext, level3

#521 TOP_LISTING FEATURES
  app.js
  controllers/listing.js
  views/includes/navbar.ejs
  views/top_listing_page.ejs
Labels: gssoc-ext, level3

#524 CUSTOM SCROLL-BAR
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, level1

#525 Display feedback toggler for admin
  app.js
  controllers/admin.js
  views/manageFeedback.ejs
Labels: gssoc-ext, level2

#528 FIX BUTTON STYLE IN SHOW LISTING
  views/show.ejs
Labels: gssoc-ext, level1

#526 FIX NAVBAR STYLE
  public/css/styles.css
  views/includes/navbar.ejs
Labels: gssoc-ext, level1

#531 Feedback display in user end
  app.js
  controllers/feedback.js
  public/css/styles.css
  views/displayFeedback.ejs
  views/includes/navbar.ejs
Labels: gssoc-ext, level3

#532 DUMMY PAYMENT INTEGRATION
  app.js
  controllers/booking.js
  models/booking.js
  views/payment.ejs
Labels: gssoc-ext, level3

#534 Fix map pop up in dark mode
  views/show.ejs
Labels: gssoc-ext, level1

#535 adding table of contents in privacy and t&c pages and enhancing them
  .gitignore
  package-lock.json
  views/privacy.ejs
  views/terms.ejs
Labels: gssoc-ext, level2

#538 adding count of how many times has the website been visited by users
  views/includes/footer.ejs
Labels: gssoc-ext, level2

#541 Add the review delete route for list in admin end
  app.js
  controllers/admin.js
  views/view_reviews.ejs
Labels: gssoc-ext, level3

#542 FIX TOP-LISTING PAGE STYLING
  views/top_listing_page.ejs
Labels: gssoc-ext, level1

#543 Add Popup Sign-in Form for Non-Logged-In Users with Time Interval Trigger (#475)
  app.js
  public/bg.jpg
  public/bg.png
  views/index.ejs
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, level3

#544 Fix index page card styling and dark mode also
  views/index.ejs
Labels: gssoc-ext, level1

#545 Admin navbar styling
  views/includes/admin_navbar.ejs
Labels: gssoc-ext, level1

#546 Change admin end feedback page into card format
  views/manageFeedback.ejs
Labels: gssoc-ext, level2

#550 Improve the UI for Welcome Section in Contributors Page (#472)
  public/css/contributor.css
Labels: gssoc-ext, level1

#552 Changes for allow maximum 3 tags for list.
  controllers/listing.js
  public/css/preloader.css
  public/js/script.js
  views/edit.ejs
  views/new.ejs
Labels: gssoc-ext, level2

#553 Restrict Access to Individual Listings for Non-Logged-In Users (#476)
  app.js
Labels: gssoc-ext, level2

#554 Add Cookie Consent Banner for User Privacy and Compliance (#477)
  views/layouts/boilerplate.ejs
Labels: gssoc-ext, level2

#556 Improve Contact Us Page UI (#492)
  public/cantact.jpg
  views/contact.ejs
Labels: gssoc-ext, level2

#560 Navigation link added
  views/login.ejs
  views/signup.ejs
Labels: gssoc-ext, level1

#561 adding dark mode and responsiveness to about us
  views/about.ejs
  views/includes/footer.ejs
Labels: gssoc-ext, level2

#562 Set the limit of 4 file input in `new.ejs` file
  app.js
  public/css/styles.css
  public/js/script.js
  views/new.ejs
Labels: gssoc-ext, level3

#563 BG-SIGNUP & LOGIN PAGE
  views/login.ejs
  views/signup.ejs
Labels: gssoc-ext, level2

#564 Set description limit for new list form, both front end and backend
  controllers/listing.js
  public/js/script.js
  views/new.ejs
Labels: gssoc-ext, level2

#567 Set the image upload limit of 4 for edit form
  app.js
  views/edit.ejs
Labels: gssoc-ext, level1

#548 Improving Footer UI (#469)
  public/css/dark_mode.css
  public/css/light_mode.css
  public/css/styles.css
  public/footer_bg.png
  public/footer_bg2.png
  public/footer_bg3.png
  views/includes/footer.ejs
Labels: gssoc-ext, level2

#555 Change Shade of Red Used Across the Website (#491)
  public/css/dark_mode.css
  public/css/light_mode.css
  public/css/preloader.css
  public/css/styles.css
  views/about.ejs
  views/adminDashboard.ejs
  views/booking.ejs
  views/contributors.ejs
  views/displayFeedback.ejs
  views/forgot-password.ejs
  views/includes/admin_navbar.ejs
  views/index.ejs
  views/manageFeedback.ejs
  views/manageUser.ejs
  views/profile.ejs
  views/show.ejs
Labels: gssoc-ext, level1

#572 Set limit of tag in admin list edit form
  controllers/admin.js
  views/edit_list_admin.ejs
  views/layouts/admin_boilerplate.ejs
Labels: gssoc-ext, level2

#573 rating number
  views/index.ejs
Labels: gssoc-ext, level1

#577 Fix admin feedback darkmode
  views/manageFeedback.ejs
Labels: gssoc-ext, level1

#575 Add Travel Stories Page (Blog) Feature (#493)
  app.js
  controllers/blog.js
  models/blog.js
  views/blog.ejs
  views/includes/footer.ejs
Labels: gssoc-ext, level3
